export const videoInfoArr = [
  {
    videoSource: "https://www.youtube.com/embed/RclT8vcrZ3s",
    title: "SS23 My Name Is",
    width: 230,
    height: 150,
    type: "Ad Work",
  },
  {
    videoSource: "https://www.youtube.com/embed/Lvu2B5BAOqQ",
    title: "Napapijri Spring/Summer '20 Choose Future - The Tribe",
    width: 230,
    height: 150,
    type: "Ad Work",
  },
  {
    videoSource:
      "https://player.vimeo.com/video/835188002?h=b894341bfe&title=0&byline=0&portrait=0",
    title: "Recess - In The Mood",
    width: 230,
    height: 150,
    type: "Ad Work",
  },
  {
    videoSource: "https://player.vimeo.com/video/716517600?h=bd3631a0d0",
    title: "Brain Freeze Flaunt",
    width: 230,
    height: 150,
    type: "Ad Work",
  },
  {
    videoSource: "https://www.youtube.com/embed/9O4ZATsPzGU",
    title: "The Hunna - Cover You ft. Travis Barker (Official Video)",
    width: 230,
    height: 150,
    type: "Music Videos",
  },
  {
    videoSource: "https://www.youtube.com/embed/agXQQDasq0U",
    title: "Doja Cat - Attention (Official Video)",
    width: 230,
    height: 150,
    type: "Music Videos",
  },
  {
    videoSource: "https://www.youtube.com/embed/GBFD4Ab3yBY",
    title: "Bazzi - Young & Alive [Official Music Video]",
    width: 230,
    height: 150,
    type: "Music Videos",
  },
  {
    videoSource: "https://www.youtube.com/embed/5fA9EmDl8nY",
    title: "iyla - 2LATE (Official Video)",
    width: 230,
    height: 150,
    type: "Music Videos",
  },
  {
    videoSource: "https://www.youtube.com/embed/a8kkXCPONL0",
    title: "aali - dreamgirl (visualizer)",
    width: 230,
    height: 150,
    type: "Music Videos",
  },
];
